<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '2cffec82183ee1cea088009cef9a6fc3' => $vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    '50b81ffc01da30f98e463592787d7917' => $vendorDir . '/jeremykendall/php-domain-parser/src/pdp-parse-url.php',
    '2c102faa651ef8ea5874edb585946bce' => $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    'ee05f3eb6cd106ac99bfaf4d0d9829d8' => $vendorDir . '/league/uri/src/functions_include.php',
    'abf2630c8f25653215b7f0ba939a13a6' => $baseDir . '/common/env.php',
);
